all:
  children:
    windows:
      hosts:
        windows-server-01:
          ansible_host: 192.168.10.108 # VagrantのIP
          ansible_user: vagrant
          ansible_password: vagrant
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_port: 5985
          ansible_winrm_scheme: http
        

  vars:
    ansible_python_interpreter: /usr/bin/python3